GET http://127.0.0.1:5001/verify/email HTTP/1.1
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRoLXNlcnZlciIsImV4cCI6MTYxNzMzMTgxNi4zOTc4MTY3LCJ1c2VyX2lkIjoieWFkb28yIn0.aeWayTFEVwOL56DQ59x1JDGe2kn5HHT1wsiuLcFd1aTqWyY80TymmkB_db2nls2eK4xV6oIuHYk9j-UC3-5C3LJef1NzYqA7N9NcRqmDEIHBlLwsbBrcVURw8tKQ81bDjqPG3Fg31j6P3lCYGe77CFRiNWL_xGloprDW3TPJy7oB2Jn8ArvKhxPdWzyilHPQ0sF6jsWA2NhmtZakcNXq1S3TzdSnYYOW5aWkHVOweE8JDImXTNtGzz2SPhtFLnJuRZPf5q_NnFzI-RyrYqp9kYdEpKU5tgQm8fIacZXP5VMRNP9fjCwr12jG69DL66sQzZTexavxdQTq40FHuKV0LA
