GET http://127.0.0.1:5002/fetch/users/ke HTTP/1.1
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRoLXNlcnZlciIsImV4cCI6MTYxODIzMjIzOC42ODI1NjgsInVzZXJfaWQiOiJrZWl0aGEifQ.hrJXbchrhp2kwXpiN8imXvVgB8fJzKahsH7KCusxD-hdy4zSl8ieiv2d7x_lVJElYMwKB1SwMjaRTHjYA7FNafwqfbMoePU46AxjKfq1_hhAyoCSqWipY-z30bh5glsdVzVnc8wv0Qdu2O6ff6YP_MMuy1FMD3_ijEwEgsBYrL63tN16RDsYIayJAV5ys9J-_itwok_N-j4FQkTg9Yxzzqb1tCL03NagkldVZGX1IPBILQOHImXwTKtBoQM1HGpVVgLxDNT15NnDqcCNrGhqcxDsGS1yeyaMc1MY7_qgCfSZEd0xpEJ7hRusCiUKgZHSqfS6LQs7CNL4Tngt30NjwA
