GET http://127.0.0.1:5001/user/profile_pic/kewl2.jpg?small=0 HTTP/1.1
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRoLXNlcnZlciIsImV4cCI6MTYxODI0NzczOS4xMzg5MDQzLCJ1c2VyX2lkIjoiaGFnZ2EifQ.HMzznDhcFC53pva37LgTjn8Q3X21TYa_Hw8lKeON90ZP3PH-5Qz3RxSDL-DHeUal6OHH9k6xP5l-s3WvvAw4csCo7PWtIsTzWvRQlRJWI1r906PcSMqmgMCDcvlJqkxtMFwqBwvAj4ABMCnuTGj_6j0zyFyEo-w7Pf8Pv4Jan96dvRrzAd72h225ea5ZO6ltRPO9vbytdvooRNmgRuj1ugeNkNI9M0v3PfVo0FaXEeTR6ES5eEmMv-z1DjgnYmv55AsMHHvIDQsRZ-MpXUeGUFEyf4kXfQP7cUtNsXAFcDbaDsjt8z61qzchJ_jT_4EwnCyHLiWX40_MXRrkxmFO5w
Content-Type: multipart/form-data