GET http://127.0.0.1:5002/connections HTTP/1.1
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRoLXNlcnZlciIsImV4cCI6MTYxODMzODQ1NS41MzExODc4LCJ1c2VyX2lkIjoia2xlcyJ9.Tbc02dhh5TO217fYVnffSTj3JBQJSJ8oiFU6kmDAMemZCnwqTcLY9bFjIA-8MQwbW_Mc0xGCP7bcZy-vTXDt2uo9FQSvrRS6MT27wSOYMgbLfiqftly0h1Zs18N0ZrjcHgX-GoLx5USEJPl7gJzPYkXVMXLsWCn80Wd7QuWHwKrCQYOCVhFgrXcBpI9KsX3nnqT7o1Lm4vEzMNZL7gbBSbp4jfDG1AIEz9ChfxYE_toa1_wEepFsN76mMAgs7AZ7yaruqGNhCwKHTXLyFTr5L4B1z8hep8uHAH7wtd0GRQHGkeSIt311a2J0IqEIrAQCUBcBbJPV9xCGcAr208AJjg
