GET http://127.0.0.1:5001/verify/token HTTP/1.1
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRoLXNlcnZlciIsImV4cCI6MTYxNzg4MjYxNS44MTM0MjgyLCJ1c2VyX2lkIjoieHl6In0.Fj_r9LL3pjgzMMVuz5C8a2aXAkyzzsr05-BTZ6hHuTOOp6ffi_1wqHrwjsW1mZMvTKFjhVQS67PtZz15FsxUGJKPR2bnemjSATcZWvVru24aKZqADPKGYq50_n2Da_JAr6WsVCdDmnMw2THHPvgWmV5W258up8Hbf6YSSPWShlWwb9W_r_Jp_nYFGh2iBgzJOCTLX0xmj6sqoQnnceRfsz1-ii5vw8PrD92GmURgQbxzzRNU_qzg4_w0Y9M2cmRTEkjEA7VkimIpCIZPURsf04JgonMXqlmNmtzEMuPICBTbABytuv4ACiOzfOxPaiXemsrx6vEskCC1iIo42PvPXg
